### ISSUE TITLE
Documentation reference issue: CORS support

### ISSUE THREAD

**Issue by ericras** [unlcms/project-herbie#877]
CORS support is being done on a per-site basis.

To enable: add a services.yml file to the site directory.  An example is in web/sites/unl.edu.information-technology-services.myred-system-status/services.yml 

```
parameters:
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['*']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['GET']
    # Configure requests allowed from specific origins. Do not include trailing
    # slashes with URLs.
    allowedOrigins: ['*']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: []
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: false
```
